version: "3.8"
services:
  node:
    image: node:18.4.0-alpine3.16
    user: node:node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - YARN_CACHE_FOLDER=/home/node/app
    command: tail -F anything
